bind 0.0.0.0

port 6379

tcp_backlog 1024

tcp_nodelay 1

timeout 300

maxmemory 268435456

maxclient 10000

client_output_buffer_limit_hard 67108864

client_output_buffer_limit_soft 16777216

appendonly yes

appendfsync everysec

appnefilename "appendonly.aof"

loglevel info